spring.application.name=roble

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ACOASMI_DE_RL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
server.address=0.0.0.0
server.port=8080
server.forward-headers-strategy=framework
spring.main.allow-bean-definition-overriding=true
